#!/bin/sh

set -e
set -x

# Create a sylius project. We can consider using -s dev flag to download a dev master Sylius version instead of the latest tagged one.
composer -n create-project sylius/sylius
mv -f sylius/* .
rm -R sylius
find {app,web} -type d -print0 | xargs -0 chmod -R 777

mv app/config/parameters.yml.dist app/config/parameters.yml

# Setup project parameters
sed -i "s/database_host: 127.0.0.1/database_host: ${SYMFONY_DATABASE_SERVER}/g" app/config/parameters.yml
sed -i "s/database_name: sylius/database_name: ${SYMFONY_DATABASE_NAME}/g" app/config/parameters.yml
sed -i "s/database_user: root/database_user: ${SYMFONY_DATABASE_USER}/g" app/config/parameters.yml
sed -i "s/database_password: null/database_password: ${SYMFONY_DATABASE_PASSWORD}/g" app/config/parameters.yml

cp app/config/parameters.yml app/config/parameters_sylius.yml

# sed -i "s/mailer_transport: null/mailer_transport: ${SYMFONY__MAILER__TRANSPORT}/g" app/config/parameters_sylius.yml
# sed -i "s/mailer_host: null/mailer_host: ${DATABASE_PASSWORD}/g" app/config/parameters_sylius.yml
# sed -i "s/mailer_user: null/mailer_user: ${DATABASE_PASSWORD}/g" app/config/parameters_sylius.yml
# sed -i "s/mailer_password: null/mailer_password: ${DATABASE_PASSWORD}/g" app/config/parameters_sylius.yml

#sed -i "s/currency: USD/currency: EUR/g" app/config/parameters_sylius.yml


sed -i "s/resource: parameters.yml/resource: parameters_sylius.yml/g" app/config/config.yml
sed -i "/^imports:/ a\    - { resource: parameters.yml }\\" app/config/config.yml

# Delete a DB Schema to ensure if it is empty. With '--no-interaction' flag sylius will try to update a current schema, so it can cause an exception.
# If we don't care about demo database demo it will be just insurance that schema does not exist.
app/console doctrine:database:drop --env=${SYMFONY_ENV} --force

# Install Sylius
app/console sylius:install --env=${SYMFONY_ENV} --no-interaction

# Loads some demo data
app/console doctrine:fixtures:load --env=${SYMFONY_ENV} --no-interaction

# In addition to these folders, we should also ensure, that: assets, bundles, css, js and media folders inside a web folder will have a proper access rights
find {app/{cache,logs,config},web} -type d -print0 | xargs -0 chmod -R 777
find web/assets -type f -print0 | xargs -0 chmod -R 0776
